[colors]
[colors.primary]
background = "#ffffff"
foreground = "#000000"

# This section controls the 'highlights' when you select text
#[colors.selection]
#text = "CellForeground"       # Keeps text black
#background = "#d0d0d0"     # Light gray highlight (standard for E-ink)

[colors.normal]
black   = "#ffffff"
red     = "#000000"
green   = "#000000"
yellow  = "#000000"
blue    = "#6d0000"
magenta = "#000000"
cyan    = "#000000"
white   = "#000000"

[colors.bright]
black   = "#494949"
red     = "#000000"          # Pure black for contrast
green   = "#000000"
yellow  = "#000000"
blue    = "#000000"
magenta = "#000000"
cyan    = "#000000"
white   = "#000000"

[colors.cursor]
text   = "#ffffff"
cursor = "#000000"
